### ISSUE TITLE
Customize position chain declaration

### ISSUE THREAD

**Issue by def-mycroft** [Graeme22/tastyworks-cli#20]
wanted to submit this issue so that the idea can percolate. 

it is often useful to arbitrarily define series of trades into a group, independently of underlying or expiration cycle. 

**for example**, last week I sold premium in $nke three days before the earnings release. this initial position was in the 22dte options chain. the day before the earnings release, I closed the original position at a small loss and opened a new position in the 1dte chain. 

**for another example**, I've been nursing a position in $/zc options for weeks. I started selling premium in expiration cycle A (call it "chain 1"), closed it out at one point, then re-opened a new position after a few days (call this one "chain 2"). both chain 1 and chain 2 contain a series of adjustments i.e. rolls within the same expiration cycle. in chain 2, I traded $/xc (mini corn futures) against my delta in a few different instances. 

in both examples, I need to calculate my breakeven price (which should include all transaction costs incurred as well as the transaction cost required to close the position). 

the first example is relatively straightforward. different positions were opened/closed in the same underlying, different expiration cycles. but, I should be able to make a decision about whether or not I want the entire string of positions to be treated as a single chain, i.e. maybe I want to segment the 22dte trade from the 1dte trade. 

the second example is more complicated. I should be able to decide whether or not the initial chain is lumped into the other chain, and also I should be able to include the trade in $/xc in the chain, at my discretion, even though it isn't technically the same underlying.

**Comment by Graeme22** [comment]
This seems like it's mostly a bookkeeping thing, so maybe something for `johnny`. That said, it would be useful to be able to list your past transactions, but filter by symbol. That's something I'd definitely like to have.
