### ISSUE TITLE
twcli - command not found

### ISSUE THREAD

**Issue by oldgitdaddy** [Graeme22/tastyworks-cli#26]
after following your installation instructions the twcli is not available as command. Please advice. 

I run the tool on raspbian OS, which should not make a big difference. Thanks!

**Comment by Graeme22** [comment]
Hi, pip typically places executable binaries in /home/user/.local/bin, so you need to have that in your PATH environment variable.

**Comment by oldgitdaddy** [comment]
$PATH already points to the particular folder. However, in the folder there is just a file named `tw`

![image](https://user-images.githubusercontent.com/4282985/153730875-bd78ea2f-bac0-4383-987a-0df1a40effe7.png)

**Comment by Graeme22** [comment]
> $PATH already points to the particular folder. However, in the folder there is just a file named `tw`
> 
> ![image](https://user-images.githubusercontent.com/4282985/153730875-bd78ea2f-bac0-4383-987a-0df1a40effe7.png)
> 

Can you do `pip list | grep cli` and post the version number?

**Comment by oldgitdaddy** [comment]
Info is:
```
click                 8.0.3
tastyworks-cli        0.1.0
```

**Comment by Graeme22** [comment]
> Info is:
> ```
> click                 8.0.3
> tastyworks-cli        0.1.0
> ```

Yup, you've got an old version. Do `pip install tastyworks-cli==1.0.3`

**Comment by oldgitdaddy** [comment]
Ok. Apparently, the package matching the particular version is not available.
```
ERROR: Could not find a version that satisfies the requirement QuantLib>=1.25 (from tastyworks-cli)
ERROR: No matching distribution found for QuantLib>=1.25

```

**Comment by Graeme22** [comment]
> Ok. Apparently, the package matching the particular version is not available.
> ```
> ERROR: Could not find a version that satisfies the requirement QuantLib>=1.25 (from tastyworks-cli)
> ERROR: No matching distribution found for QuantLib>=1.25
> 
> ```

That's weird, because the latest version of QuantLib is definitely 1.25... Is your pip up to date?
